config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/search', to: 'videos#search'

  devise_for :users

  resources :users do 
    resources :favorites, only: [:index, :create, :destroy]
  end

  delete '/users/:id/favorites', to: 'favorites#index'

  resources :favorites do
    resources :comments
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :body, presence: true

	belongs_to :user
	belongs_to :favorite
	
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  # Relationships
	belongs_to :user
	has_many :comments, dependent: :destroy #deletes comments if favorite is destroyed	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Relationships
  has_many :videos, through: :favorites  #deletes all favorites if user is destroyed
  has_many :favorites  # has_many :fav_videos, through: :favorites, source: :videos
  has_many :comments, dependent: :destroy  # deletes all comments if user is destroyed

end

app/models/video.rb
class Video < ActiveRecord::Base
	has_many :favorites
	has_many :users, through: :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@favorite = Favorite.find(params[:favorite_id])
		@comment = @favorite.comments.create(comment_params)

		if @comment.save 
			flash[:success] = "Comment saved."
			redirect_to favorites_path
		end
	end

	def edit
		render 'edit'
	end

	def update		
		authorize @comment
		if @comment.update(comment_params)
			redirect_to @comment
		else
			render :edit
		end
	end

	def destroy
		@favorite = Favorite.find(params[:favorite_id])
    @comment = @favorite.comments.find(params[:id])
    @comment.destroy
    redirect_to @favorite
  end

    private

    def comment_params
   	 params.require(:comment).permit(:body) 
		end

  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
		before_action :find_favorite, only: [:show]
		before_action :authenticate_user!

	def index
		@user = current_user
		# @videos = @user.videos.all
  # 	@user = current_user
		@favorites = current_user.favorites
		# Pass object that contains both the video url & the favorite id to the view
		@video_favs = @favorites.map do |favorite|
			{ fav_id: favorite.id, video_url: Video.find(favorite.video_id).url }
		end
		render :index
	end

	def create
		# Create the video
		@video = Video.create({url: params[:url]})
		# Create the favorite association
		current_user.favorites.create({video_id: @video.id, user_id: current_user.id})
		flash.now[:alert] = 'weee'
		redirect_to user_favorites_path(current_user)
	end

	def destroy
		# Find favorite
		favorite = Favorite.find(params[:id])
		# Delete favorite from user's favorites
		favorite.destroy

		# Redirect back to user's favorites page
		# redirect_to :back, method: :get # still not reloading...
		redirect_to user_favorites_path(current_user.id)
	end

private
	
	def find_favorite
		@favorite = Favorite.find(params[:id])
	end

	def favorite_params
		params.require(:favorite).permit(:user_id, :url, :video_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 #  def show
 #  	@user = User.find(params[:id])
	# end

  def new
  	@user = User.new
  	render :new
  end

  def create
  	@user = User.create(user_params)
  	redirect_to user_path(@user.id)
  end

  def edit
  end

  # def edit
  #   render 'edit'
  # end

  # def update    
  #   authorize @comment
  #   if @comment.update(comment_params)
  #     redirect_to @comment
  #   else
  #     render :edit
  #   end
  # end

private
  def user_params
    params.require(:user)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :authenticate_user!

  def index
  	@videos = @user.videos.all
  	# render :index
  end

  def search
		dev_key = 'AI39si79lSHUqU8o_xFVcG3h6YyAbMbnoBatUqb8mA45r_t-D47Wp_JK9a-xPHuNjrlQa27aEvhRMomNBg4nF93s6KMSriPCNQ'

  	search_term = params[:search]
  	search = Typhoeus.get(
  		'https://gdata.youtube.com/feeds/api/videos',
  		params: {
  			q: search_term,
  			category: 'Education',
  			key: dev_key,
  			alt: 'json'
  		}
  	)

  	response = JSON.parse(search.body)

		results = response["feed"]["entry"]

		#Get Video IDs from YouTube API (e.g. "-")
		ids = results.map do |result|
			result["id"]["$t"].split("/")[6]
		end

		#Pass the view only the first 10
		@ids = ids.first(10)
	end

	def new
		@video = Video.new
	end

	def create
		@video = Video.new(params.require(:video))
		@video.user = current_user
	end

	def destroy
		@video.destroy
	end

		# @result = @results["feed"]["entry"][0]["link"][0]["href"]

		# render :json => @results

end




# <% 1.upto(10).each do |n| %>

# 	<embed width="420" height="315" src="<%= @results[n]["link"][0]["href"] %>">


# <% end %>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<tr>
	<td>
		<%= comment.body %>
	</td>
	<td>
		<span><%= link_to 'X', [comment.favorite, comment],
					method: :delete,
					data: { confirm: "Are you sure?" },
					class: "btn btn-danger" %></span>
	</td>
</tr>

app/views/favorites/_comment_form.html.erb
<div class="custom-comment-form">
	<% @favorites.reverse.each do |favorite| %>
		<div class="fav-form">
			<%= form_for([favorite, favorite.comments.build]) do |f| %>
				<p>
				 <%= f.text_area :body, :class => 'fav-form-text' %>
				</p>
				<p>
				 <%= f.submit 'Submit', :class => 'btn btn-default' %>
				</p>
			<% end %>
			<br>
		<% favorite.comments.reverse.each do |comment| %>
		  <p>
		    <%= comment.body %>
		  </p>
		<% end %>
		</div>
	<% end %>
</div>

app/views/favorites/index.html.erb
<div class="container">
	<div class="row">
		<div class="text-center col-md-6-offset-3">
			<h2><%= @user.email %>'s Favorite Tutorials</h2>
		</div>
	</div>
</div>

<br>

<div class="container">
	<div class="row">
		<div class="col-md-6-offset-3 center-video-divs">
			<%= render 'comment_form' %>
			<div class="videos">
				<% @video_favs.reverse.each do |video_fav| %>
					<iframe width="420" height="315" src="<%=video_fav[:video_url]%>" frameborder="0" allowfullscreen></iframe>
					<br>
					<%= link_to 'Delete', user_favorite_path(current_user, video_fav[:fav_id]), method: :delete, :class => 'btn btn-danger video-favs' %>
					<br>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<!-- Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                    	<%= render 'layouts/flash' %>

                        	<h2>What do you want to learn?</h2>
                        <!-- SEARCH BOX -->
                        	<div>
                        		<%= form_tag search_path, :method => 'get', class: 'form-group' do %>
                          		<p>
                          			<div class="search-field">
                            			<%= text_field_tag :search, params[:search], class: 'form-control', :placeholder => "e.g. Ruby on rails, Angular.js, etc." %>
                            		</div>
                        	    		<%= submit_tag "Search", class: "btn btn-lg btn-default vid-search" %>
                          	</p>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Team Me How To Code</h2>
                <p>Add your about content here, find me in home/index.html (in views).</p>
            </div>
        </div>
    </section>

app/views/layouts/_flash.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top nav-padding" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="/">
                <i class="fa fa-play-circle"></i>  <span class="light">Teach me</span> how to code
            </a><br>
            <% if user_signed_in? %>
                <%= current_user.email %>
            <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <% if current_page?(root_path) %>
                        <a class="page-scroll" href="#about">About</a>
                    <% end %>
                </li>
                <% if user_signed_in? %>
                <% unless current_page?(user_favorites_path(current_user)) %>
                <li>
                    <%= link_to "Favorites", user_favorites_path(current_user), method: :get, :class => 'navbar-link' %>
                </li>
                <% end %>
                <% unless current_page?(root_path) %>
                <li>
                    <%= link_to "Search", root_path(current_user), method: :get, :class => 'navbar-link' %>
                </li>
                <% end %>
                <li>
                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
                </li>
                <li>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top" class="<% if current_page?(root_path) %><% else %>padding-top<% end %>">

<%= render 'layouts/navigation' %>

<%= yield %>

</body>
</html>

app/views/videos/index.html.erb
<% @ids.each do |id| %>

	
	<br><iframe width="420" height="315" src="https://www.youtube.com/embed/<%=id%>" frameborder="0" allowfullscreen></iframe>

<% end %>

app/views/videos/search.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6-offset-3 text-center">
		<h1>Top results for "<%= params[:search] %>"</h1>
		
		<% @ids.each do |id| %>
		
			<iframe width="420" height="315" src="https://www.youtube.com/embed/<%= id %>" frameborder="0" allowfullscreen></iframe>
		
			<% url = 'https://www.youtube.com/embed/' + id.to_s %>
			
			<%= form_tag user_favorites_path(current_user), method: :post do %>
				<%= hidden_field_tag 'user_id', current_user.id %>
				<%= hidden_field_tag 'video_id', id %>
				<%= hidden_field_tag 'url', url %> 	<!-- taken from favorites schema -->
		
				<%= submit_tag 'Save to Faves', class: "btn btn-default btn-lg fav-save" %>
			<% end %>
		
		<% end %>
		</div>
	</div>
</div>